//! Read-path conformance.
//!
//! Two distinct claims are tested, and they are not the same thing:
//!
//! 1. **Round-trip.** What `BgzfWriter` writes, `BgzfReader` reads back. This catches internal
//!    inconsistency but would still pass if both sides shared the same misunderstanding of the
//!    format.
//! 2. **Cross-implementation.** Files produced by *htsjdk itself* decode to the right bytes.
//!    This is the claim that matters, and it is why the fixtures are generated by the oracle
//!    rather than by this crate.
//!
//! Fixtures are produced by `tools/bgzf-conformance/MakeFixtures.java` run through
//! `tools/oracle/run.sh`, and committed under `tests/fixtures/`.

use std::io::{Read, Write};

use htsjdk_bgzf::{vfp, BgzfReader, BgzfWriter};

fn lcg(n: usize, seed: u64, shift: u32) -> Vec<u8> {
    let mut b = vec![0u8; n];
    let mut s = seed;
    for x in b.iter_mut() {
        s = s
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        *x = (s >> shift) as u8;
    }
    b
}

fn runs(n: usize) -> Vec<u8> {
    (0..n).map(|i| ((i / 64) % 7) as u8).collect()
}

fn text(n: usize) -> Vec<u8> {
    let p = b"ACGTNacgtn\tSAMrecord\n";
    (0..n).map(|i| p[i % p.len()]).collect()
}

fn payload(name: &str) -> Vec<u8> {
    match name {
        "empty" => Vec::new(),
        "tiny" => text(10),
        "exact1" => runs(65498),
        "over1" => runs(65499),
        "multi" => lcg(200_000, 12345, 58),
        "incompr" => lcg(200_000, 999, 56),
        "big" => text(500_000),
        other => panic!("unknown payload {other}"),
    }
}

const CASES: &[&str] = &[
    "empty", "tiny", "exact1", "over1", "multi", "incompr", "big",
];

fn write_bgzf(input: &[u8], level: u32) -> Vec<u8> {
    let mut w = BgzfWriter::with_level(Vec::new(), level);
    w.write_all(input).unwrap();
    w.into_inner().unwrap()
}

fn read_bgzf(bytes: &[u8]) -> Vec<u8> {
    let mut out = Vec::new();
    BgzfReader::new(bytes).read_to_end(&mut out).unwrap();
    out
}

#[test]
fn round_trips_every_payload_at_every_level() {
    for &name in CASES {
        let original = payload(name);
        for level in [0u32, 1, 5, 6, 9] {
            let encoded = write_bgzf(&original, level);
            let decoded = read_bgzf(&encoded);
            assert_eq!(
                decoded.len(),
                original.len(),
                "length mismatch for `{name}` at level {level}"
            );
            assert!(
                decoded == original,
                "content mismatch for `{name}` at level {level}"
            );
        }
    }
}

/// Decoding files written by htsjdk itself. This is the claim that round-tripping cannot make.
#[test]
fn decodes_files_written_by_htsjdk() {
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    if !dir.exists() {
        panic!(
            "fixtures missing at {}; generate them with \
             tools/oracle/run.sh ../bgzf-conformance/MakeFixtures.java",
            dir.display()
        );
    }
    let mut checked = 0;
    for &name in CASES {
        for level in [0u32, 1, 5, 6, 9] {
            let path = dir.join(format!("{name}_l{level}.bgzf"));
            let bytes =
                std::fs::read(&path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
            let decoded = read_bgzf(&bytes);
            let expected = payload(name);
            assert!(
                decoded == expected,
                "decoded htsjdk fixture `{name}` at level {level} did not match the source payload"
            );
            checked += 1;
        }
    }
    assert_eq!(checked, CASES.len() * 5);
}

/// The bytes htsjdk writes and the bytes we write must be the same file, so reading either
/// with either reader must agree. This pins writer and reader together against the oracle.
#[test]
fn our_encoding_matches_the_htsjdk_fixture_byte_for_byte() {
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    for &name in CASES {
        for level in [0u32, 1, 5, 6, 9] {
            let path = dir.join(format!("{name}_l{level}.bgzf"));
            let theirs = std::fs::read(&path).unwrap();
            let ours = write_bgzf(&payload(name), level);
            assert!(
                ours == theirs,
                "byte mismatch against htsjdk fixture `{name}` at level {level}: \
                 ours {} bytes, theirs {} bytes",
                ours.len(),
                theirs.len()
            );
        }
    }
}

#[test]
fn empty_stream_yields_no_bytes() {
    let encoded = write_bgzf(&[], 5);
    assert_eq!(read_bgzf(&encoded), Vec::<u8>::new());
}

#[test]
fn block_addresses_advance_and_are_representable_as_virtual_pointers() {
    let encoded = write_bgzf(&payload("multi"), 5);
    let mut r = BgzfReader::new(&encoded[..]);
    let mut addresses = Vec::new();
    while let Some(b) = r.next_block().unwrap() {
        if b.data.is_empty() {
            break; // terminator
        }
        addresses.push(b.block_address);
    }
    assert!(addresses.len() > 1, "expected several blocks");
    assert!(
        addresses.windows(2).all(|w| w[0] < w[1]),
        "block addresses must strictly increase"
    );
    for a in addresses {
        let p = vfp::make_file_pointer(a, 0).unwrap();
        assert_eq!(vfp::block_address(p), a);
    }
}

#[test]
fn rejects_a_truncated_block() {
    let mut encoded = write_bgzf(&payload("tiny"), 5);
    encoded.truncate(encoded.len() / 2);
    let mut out = Vec::new();
    assert!(
        BgzfReader::new(&encoded[..]).read_to_end(&mut out).is_err(),
        "a truncated stream must be rejected"
    );
}

#[test]
fn rejects_a_corrupt_gzip_header() {
    let mut encoded = write_bgzf(&payload("tiny"), 5);
    encoded[0] = 0x00; // break GZIP_ID1
    let mut out = Vec::new();
    assert!(BgzfReader::new(&encoded[..]).read_to_end(&mut out).is_err());
}

/// CRC checking is off by default, matching `BlockGunzipper.checkCrcs = false`. A reader that
/// always verified would reject files htsjdk accepts, so the default must stay permissive and
/// the strict mode must be opt-in and actually work.
#[test]
fn crc_checking_is_opt_in_and_effective() {
    let mut encoded = write_bgzf(&payload("tiny"), 5);
    let len = encoded.len();
    // The footer of the first (and only) data block sits just before the 28-byte terminator.
    let crc_pos = len - 28 - 8;
    encoded[crc_pos] ^= 0xFF;

    let mut lenient = Vec::new();
    assert!(
        BgzfReader::new(&encoded[..])
            .read_to_end(&mut lenient)
            .is_ok(),
        "default reader must ignore a bad CRC, as htsjdk does"
    );

    let mut strict_reader = BgzfReader::new(&encoded[..]);
    strict_reader.set_check_crcs(true);
    let mut strict = Vec::new();
    assert!(
        strict_reader.read_to_end(&mut strict).is_err(),
        "opt-in CRC checking must reject a corrupted block"
    );
}
